### ISSUE TITLE
How to use renderer/viewer.html?

### ISSUE THREAD

**Issue by canadaduane** [radian628/raymarching-engine#1]
Hi! This is a cool project you have going here. I was just passing by and wondered how to get the renderer or viewer html files working. I tried loading them in a browser, but it appears there is more to it than just opening the page :)

**Comment by radian628** [comment]
Thanks for the question! If you downloaded the repo and tried to directly open it from a file, you're likely getting a CORS error, because cross-origin requests don't work for local files (despite the fact that it's trying to open another local file, not a resource from a different site). The way to fix this is to run a web server to serve up the files. This is relatively easy to set up- I found [a VSCode plugin](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer) that seems to work. 

Hope this helps!

**Comment by canadaduane** [comment]
Indeed it does! Thanks for the tip. I explored a few of your worlds and it's kind of wild! Not only the colors and ethereal nature of the space, but also the tech you're using. Quite impressive. Thanks for sharing (and explaining :)

**Comment by radian628** [comment]
Thank you! Glad to see that the web server worked!
